JapaneWebsite/Areas/Admin/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JapaneWebsite;

namespace JapaneWebsite.Areas.Admin.Controllers
{
    [Authorize(Roles = "MANAGER,ADMIN")]
    public class PlacesController : Controller
    {

        private JapaneDataEntities db = new JapaneDataEntities();

        // GET: Admin/Places
        public ActionResult Index()
        {
            return View(db.Places.ToList());
        }

        // GET: Admin/Places/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // GET: Admin/Places/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Places/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPlace,CityName,Detail")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Places.Add(place);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(place);
        }

        // GET: Admin/Places/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Admin/Places/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPlace,CityName,Detail")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Entry(place).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(place);
        }
        [Authorize(Roles = "ADMIN")]
        // GET: Admin/Places/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Admin/Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Place place = db.Places.Find(id);
            db.Places.Remove(place);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JapaneWebsite/Areas/Admin/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JapaneWebsite;

namespace JapaneWebsite.Areas.Admin.Controllers
{
    [Authorize(Roles = "MANAGER,ADMIN")]
    public class QuestionsController : Controller
    {
        private JapaneDataEntities db = new JapaneDataEntities();

        // GET: Admin/Questions
        public ActionResult Index()
        {
            var questions = db.Questions.Include(q => q.Test);
            return View(questions.ToList());
        }

        // GET: Admin/Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Admin/Questions/Create
        public ActionResult Create()
        {
            ViewBag.IdTest = new SelectList(db.Tests, "IdTest", "Name");
            return View();
        }

        // POST: Admin/Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdQuestion,IdTest,Name,Option1,Option2,Option3,Option4,Answer")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdTest = new SelectList(db.Tests, "IdTest", "Name", question.IdTest);
            return View(question);
        }

        // GET: Admin/Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdTest = new SelectList(db.Tests, "IdTest", "Name", question.IdTest);
            return View(question);
        }

        // POST: Admin/Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdQuestion,IdTest,Name,Option1,Option2,Option3,Option4,Answer")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdTest = new SelectList(db.Tests, "IdTest", "Name", question.IdTest);
            return View(question);
        }
        [Authorize(Roles = "ADMIN")]
        // GET: Admin/Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Admin/Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JapaneWebsite/Areas/Admin/Controllers/StudyPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JapaneWebsite;
using PagedList;

namespace JapaneWebsite.Areas.Admin.Controllers
{
    [Authorize(Roles = "MANAGER,ADMIN")]
    public class StudyPostsController : Controller
    {
        private JapaneDataEntities db = new JapaneDataEntities();

        // GET: Admin/StudyPosts
        public ActionResult Index(int? Page_No, int? cateId, int Size_Of_Page = 4)
        {
            int Number_Of_Page = (Page_No) ?? 1;
            var studyPosts = db.StudyPosts.Include(s => s.Level).Include(s => s.ThemeOfPost).OrderBy(s => s.IdStudyPost).ToPagedList(Number_Of_Page, Size_Of_Page);
            return View(studyPosts);
        }

        // GET: Admin/StudyPosts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudyPost studyPost = db.StudyPosts.Find(id);
            if (studyPost == null)
            {
                return HttpNotFound();
            }
            return View(studyPost);
        }

        // GET: Admin/StudyPosts/Create
        public ActionResult Create()
        {
            ViewBag.N = new SelectList(db.Levels, "N", "N");
            ViewBag.IdThemePost = new SelectList(db.ThemeOfPosts, "IdThemePost", "Name");
            return View();
        }

        // POST: Admin/StudyPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdStudyPost,Name,Description,Date,Img,Detail,N,IdThemePost")] StudyPost studyPost)
        {
            if (ModelState.IsValid)
            {
                db.StudyPosts.Add(studyPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.N = new SelectList(db.Levels, "N", "N", studyPost.N);
            ViewBag.IdThemePost = new SelectList(db.ThemeOfPosts, "IdThemePost", "Name", studyPost.IdThemePost);
            return View(studyPost);
        }

        // GET: Admin/StudyPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudyPost studyPost = db.StudyPosts.Find(id);
            if (studyPost == null)
            {
                return HttpNotFound();
            }
            ViewBag.N = new SelectList(db.Levels, "N", "N", studyPost.N);
            ViewBag.IdThemePost = new SelectList(db.ThemeOfPosts, "IdThemePost", "Name", studyPost.IdThemePost);
            return View(studyPost);
        }

        // POST: Admin/StudyPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdStudyPost,Name,Description,Date,Img,Detail,N,IdThemePost")] StudyPost studyPost)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studyPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.N = new SelectList(db.Levels, "N", "N", studyPost.N);
            ViewBag.IdThemePost = new SelectList(db.ThemeOfPosts, "IdThemePost", "Name", studyPost.IdThemePost);
            return View(studyPost);
        }
        [Authorize(Roles = "ADMIN")]
        // GET: Admin/StudyPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudyPost studyPost = db.StudyPosts.Find(id);
            if (studyPost == null)
            {
                return HttpNotFound();
            }
            return View(studyPost);
        }

        // POST: Admin/StudyPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StudyPost studyPost = db.StudyPosts.Find(id);
            db.StudyPosts.Remove(studyPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JapaneWebsite/Areas/Admin/Controllers/ThemeOfPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JapaneWebsite;

namespace JapaneWebsite.Areas.Admin.Controllers
{
    [Authorize(Roles = "MANAGER,ADMIN")]
    public class ThemeOfPostsController : Controller
    {
        private JapaneDataEntities db = new JapaneDataEntities();

        // GET: Admin/ThemeOfPosts
        public ActionResult Index()
        {
            return View(db.ThemeOfPosts.ToList());
        }

        // GET: Admin/ThemeOfPosts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThemeOfPost themeOfPost = db.ThemeOfPosts.Find(id);
            if (themeOfPost == null)
            {
                return HttpNotFound();
            }
            return View(themeOfPost);
        }

        // GET: Admin/ThemeOfPosts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/ThemeOfPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdThemePost,Name,Detail")] ThemeOfPost themeOfPost)
        {
            if (ModelState.IsValid)
            {
                db.ThemeOfPosts.Add(themeOfPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(themeOfPost);
        }

        // GET: Admin/ThemeOfPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThemeOfPost themeOfPost = db.ThemeOfPosts.Find(id);
            if (themeOfPost == null)
            {
                return HttpNotFound();
            }
            return View(themeOfPost);
        }

        // POST: Admin/ThemeOfPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdThemePost,Name,Detail")] ThemeOfPost themeOfPost)
        {
            if (ModelState.IsValid)
            {
                db.Entry(themeOfPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(themeOfPost);
        }
        [Authorize(Roles = "ADMIN")]
        // GET: Admin/ThemeOfPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThemeOfPost themeOfPost = db.ThemeOfPosts.Find(id);
            if (themeOfPost == null)
            {
                return HttpNotFound();
            }
            return View(themeOfPost);
        }

        // POST: Admin/ThemeOfPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ThemeOfPost themeOfPost = db.ThemeOfPosts.Find(id);
            db.ThemeOfPosts.Remove(themeOfPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JapaneWebsite/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quản Lý</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Plugin/ckeditor/ckeditor.js"></script>
    @*<script src="//cdn.ckeditor.com/4.11.4/full/ckeditor.js"></script>*@
    <script src="~/Plugin/ckfinder/ckfinder.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/v4-shims.css">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            z-index: 100; /* Behind the navbar */
            padding: 48px 0 0; /* Height of navbar */
            box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
        }

        .sidebar-sticky {
            position: relative;
            top: 0;
            height: calc(100vh - 48px);
            padding-top: .5rem;
            overflow-x: hidden;
            overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
        }

        .sidebar .nav-link {
            font-weight: 500;
            color: #333;
        }

            .sidebar .nav-link .feather {
                margin-right: 4px;
                color: #999;
            }

            .sidebar .nav-link.active {
                color: #007bff;
            }

                .sidebar .nav-link:hover .feather,
                .sidebar .nav-link.active .feather {
                    color: inherit;
                }

        .sidebar-heading {
            font-size: .75rem;
            text-transform: uppercase;
        }

        /*
        * Content
        */

        [role="main"] {
            padding-top: 133px; /* Space for fixed navbar */
        }

        .navbar-brand {
            padding-top: .75rem;
            padding-bottom: .75rem;
            font-size: 1rem;
            background-color: rgba(0, 0, 0, .25);
            box-shadow: inset -1px 0 0 rgba(0, 0, 0, .25);
        }

        .navbar .form-control {
            padding: .75rem 1rem;
            border-width: 0;
            border-radius: 0;
        }

        .form-control-dark {
            color: #fff;
            background-color: rgba(255, 255, 255, .1);
            border-color: rgba(255, 255, 255, .1);
        }

            .form-control-dark:focus {
                border-color: transparent;
                box-shadow: 0 0 0 3px rgba(255, 255, 255, .25);
            }

        .my1 {
            color: white;
        }
    </style>

</head>
<body>
    @*<div class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav"></ul>
                </div>
            </div>
            <div class="container">
                <!-- responsive-nav -->
                <div id="responsive-nav">
                    <!-- NAV -->
                    <ul class="main-nav nav navbar-nav">
                        @Html.ActionLink("Theme of Post", "Index", "ThemeOfPosts") |
                        @Html.ActionLink("Study Post", "Index", "StudyPosts") |
                        @Html.ActionLink("Cultural Post", "Index", "CulturalPosts") |
                        @Html.ActionLink("Place", "Index", "Places") |
                        @Html.ActionLink("Tests", "Index", "Tests") |
                        @Html.ActionLink("Question", "Index", "Questions") |

                    </ul>
                    <!-- /NAV -->
                </div>
                <!-- /responsive-nav -->
            </div>
        </div>*@
    @*<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
            @Html.ActionLink("JAPANE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown active">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Page
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="~/Admin/ThemeOfPosts/Index">Theme of Post</a>
                            <a class="dropdown-item" href="~/Admin/StudyPosts/Index">Study Post</a>
                            <a class="dropdown-item" href="#">Cultural Post</a>
                            <a class="dropdown-item" href="#">Place</a>
                            <a class="dropdown-item" href="#">Tests</a>
                            <a class="dropdown-item" href="#">Question</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>*@
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="~/">JAPANE</a>
        @*<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">*@
        @*<ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">*@
                @using Microsoft.AspNet.Identity
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <ul class="navbar-nav px-4 ">
                            <li class="nav-item active">@Html.ActionLink("Welcome " + User.Identity.GetUserName() + "!", "Index", "Manage", new { area = "" }, htmlAttributes: new { title = "Manage" , @class = "my1"})</li>
                            <li class="nav-item active"><a href="javascript:document.getElementById('logoutForm').submit()" class="my1">Log Out</a></li>
                        </ul>
                    }
                }
                @*</li>
        </ul>*@
    </nav>
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link active" href="~/Admin/Dashboard/Index">
                        <i class="fas fa-home"></i>
                        <span data-feather="home"></span>
                        Dashboard <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Admin/StudyPosts/Index">
                        <i class="fas fa-file"></i>
                        <span data-feather="file"></span>
                        Study Posts
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Admin/CulturalPosts/Index">
                        <i class="fas fa-file"></i>
                        <span data-feather="shopping-cart"></span>
                        Culture Posts
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Admin/Places/Index">
                        <i class="fas fa-file"></i>
                        <span data-feather="users"></span>
                        Places
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Admin/ThemeOfPosts/Index">
                        <i class="fas fa-file"></i>
                        <span data-feather="bar-chart-2"></span>
                        Theme Of Posts
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Admin/Tests/Index">
                        <i class="fas fa-file"></i>
                        <span data-feather="layers"></span>
                        Tests
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Admin/Questions/Index">
                        <i class="fas fa-file"></i>
                        <span data-feather="layers"></span>
                        Questions
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    @RenderBody()

    <script defer src="https://use.fontawesome.com/releases/v5.9.0/js/all.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.9.0/js/v4-shims.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>