JapaneWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JapaneWebsite;
using JapaneWebsite.Models;

namespace JapaneWebsite.Controllers
{
    public class HomeController : Controller
    {
        private JapaneDataEntities db = new JapaneDataEntities();
        // GET: Home
        public List<StudyPost> GetStudyPost()
        {
            return db.StudyPosts.OrderByDescending(s => s.IdStudyPost).Take(3).ToList();
        }
        public List<ThemeOfPost> GetThemeOfPosts()
        {
            return db.ThemeOfPosts.OrderByDescending(s => s.IdThemePost).ToList(); ;
        }
        public List<CulturalPost> GetCulturalPosts()
        {
            return db.CulturalPosts.OrderByDescending(s => s.IdCultural).Take(3).ToList();
        }
        public List<Test> GetTestPosts()
        {
            return db.Tests.OrderByDescending(s => s.IdTest).Take(3).ToList();
        }

        public ActionResult Index()
        {
            ViewModel model = new ViewModel();
            model.studyPosts = GetStudyPost();
            model.themeOfPosts = GetThemeOfPosts();
            model.culturalPosts = GetCulturalPosts();
            model.Tests = GetTestPosts();
            return View(model);
        }
    }
}

JapaneWebsite/Controllers/LearningPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JapaneWebsite;
using PagedList;

namespace JapaneWebsite.Controllers
{
    public class LearningPostsController : Controller
    {
        private JapaneDataEntities db = new JapaneDataEntities();

        // GET: LearningPosts
        public ActionResult Index(int? Page_No, int Size_Of_Page = 5)
        {
            int Number_Of_Page = (Page_No) ?? 1;
            var studyPosts = db.StudyPosts.Include(s => s.Level).Include(s => s.ThemeOfPost).OrderBy(s => s.IdStudyPost).ToPagedList(Number_Of_Page, Size_Of_Page);
            return View(studyPosts);
        }

        // GET: LearningPosts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudyPost studyPost = db.StudyPosts.Find(id);
            if (studyPost == null)
            {
                return HttpNotFound();
            }
            return View(studyPost);
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JapaneWebsite/Controllers/SearchController.cs
using JapaneWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace JapaneWebsite.Controllers
{
    public class SearchController : Controller
    {
        private JapaneDataEntities db = new JapaneDataEntities();
        // GET: Search
        public List<StudyPost> GetStudyPost(string SearchString)
        {
            return db.StudyPosts.Where(s=>s.Name.Contains(SearchString)).ToList();
        }
        public List<CulturalPost> GetCulturalPosts(string SearchString)
        {
            return db.CulturalPosts.Where(s => s.Name.Contains(SearchString)).ToList();
        }
    

        public List<StudyPost> GetStudyPostByThemeOfPost(int? id,string name)
        {

            return db.StudyPosts.Where(s => s.IdThemePost == id || s.Name.Contains(name)).ToList();
        }

        public List<CulturalPost> GetCulturalByThemeOfPost(int? id,string name)
        {

            return db.CulturalPosts.Where(s => s.IdThemePost == id||s.Name.Contains(name)).ToList();
        }

        public List<Volcabulary> GetVolcabularies(string name)
        {

            return db.Volcabularies.Where(s=>s.Kanji.Contains(name) || s.Furigana.Contains(name) || s.Meaning.Contains(name)).ToList();
        }
        public List<Volcabulary> GetVolcabulariesByLevel(string name)
        {

            return db.Volcabularies.Where(s=>s.N.Contains(name)).ToList();
        }
        public ActionResult Index(string SearchString)
        {
            if (String.IsNullOrEmpty(SearchString))
            {
                SearchString = "";
            }
            ViewModel model = new ViewModel();
            model.studyPosts = GetStudyPost(SearchString);
            model.culturalPosts = GetCulturalPosts(SearchString);
            model.volcabularies = GetVolcabularies(SearchString);
            return View(model);
        }
        public ActionResult IndexByLevel(string SearchString)
        {
            if (String.IsNullOrEmpty(SearchString))
            {
                SearchString = "";
            }
            ViewModel model = new ViewModel();
            model.volcabularies = GetVolcabulariesByLevel(SearchString);
            return View(model);
        }
        public ActionResult IndexByTheme(int? id,string name)
        {
        
            ViewModel model = new ViewModel();

            model.culturalPosts = GetCulturalByThemeOfPost(id, name);
            model.studyPosts = GetStudyPostByThemeOfPost(id,name);
            return View(model);
        }

        public List<StudyPost> GetAllGrammar(string name)
        {
            return db.StudyPosts.Where(s => s.Name.Contains(name)).OrderBy(s => s.IdStudyPost).ToList();
        }



        public ActionResult GroupPost(string name)
        {
            ViewModel model = new ViewModel();
            model.studyPosts = GetAllGrammar(name);
            return View(model);
        }

    }
}

JapaneWebsite/Controllers/TraditionPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JapaneWebsite;
using PagedList;

namespace JapaneWebsite.Controllers
{
    public class TraditionPostsController : Controller
    {
        private JapaneDataEntities db = new JapaneDataEntities();

        // GET: TraditionPosts
        public ActionResult Index(int? Page_No, int? cateId, int Size_Of_Page = 8)
        {
            int Number_Of_Page = (Page_No) ?? 1;
            var culturalPosts = db.CulturalPosts.Include(c => c.Place).Include(c => c.ThemeOfPost).OrderBy(s => s.IdCultural).ToPagedList(Number_Of_Page, Size_Of_Page);
            return View(culturalPosts);
        }

        // GET: TraditionPosts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CulturalPost culturalPost = db.CulturalPosts.Find(id);
            if (culturalPost == null)
            {
                return HttpNotFound();
            }
            return View(culturalPost);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JapaneWebsite/Views/Home/Index.cshtml
@model JapaneWebsite.Models.ViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ShareLayout.cshtml";
}
<div class="container-fluid" style="margin-top:80px">
    <div class="row">
        <div class="col-sm-9">
            <div class="card shadow">
                <div class="card-header" style="height:50px">
                    <h4>Hình ảnh đẹp</h4>
                </div>
                <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active" data-interval="10000">
                            <img src="https://source.unsplash.com/1600x900/?sakura" class="d-block w-100 img-slider" alt="...">
                        </div>
                        <div class="carousel-item" data-interval="2000">
                            <img src="https://source.unsplash.com/1600x900/?water" class="d-block w-100 img-slider" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="https://source.unsplash.com/1600x900/?japan" class="d-block w-100 img-slider" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="https://source.unsplash.com/1600x900/?kyoto" class="d-block w-100 img-slider" alt="...">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <hr  />
            <div class="card shadow">
                <div class="card-header" style="height:50px;">
                    <h4>Học tiếng Nhật</h4>
                </div>
                @Html.Partial("_ArticleHocTiengNhat", Model)

                <div class="card-footer text-right" style="">

                    @Html.ActionLink("Xem thêm", "Index", "LearningPosts", null, new { @class = "card-link" })
                </div>
            </div>
            <hr />
            <div class="card shadow">
                <div class="card-header" style="height:50px">
                    <h4>Văn hóa</h4>
                </div>
                @Html.Partial("_ArticleVanHoaNhat", Model)

                <div class="card-footer text-right" style="">
                    @Html.ActionLink("Xem thêm", "Index", "TraditionPosts", null, new { @class = "card-link" })
                </div>
            </div>
            <hr />
            <div class="card shadow">
                <div class="card-header" style="height:50px;">
                    <h4>Thi Thử JLPT</h4>
                </div>
                @Html.Partial("_ArticleTest", Model)
                <div class="card-footer text-right" style="">
                    @Html.ActionLink("Xem thêm", "Index", "Dotest", null, new { @class = "card-link" })
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            @Html.Partial("_Aside", Model)
            <br />
            <div class="card">
                <h4 class="card-header text-center" style="">Bài Viết</h4>
                <div class="card-body">
                    <h6 class="card-title">Tổng hợp ngữ pháp N5</h6>
                    <p class="card-text" style="overflow:hidden">Đây là bài tổng hợp tất cả ngữ pháp N5 có được</p>
                    <a href="@Url.Action("GroupPost","Search",new { name="N5"})" class="btn btn-primary">Tiếp tục</a>
                </div>
                <hr />
                <div class="card-body">
                    <h6 class="card-title">Tổng hợp ngữ pháp N4</h6>
                    <p class="card-text" style="overflow:hidden">Đây là bài tổng hợp tất cả ngữ pháp N4 có được</p>
                    <a href="@Url.Action("GroupPost","Search",new { name="N4"})" class="btn btn-primary">Tiếp tục</a>
                </div>
                <hr />
                <div class="card-body">
                    <h6 class="card-title">Tổng hợp ngữ pháp N3</h6>
                    <p class="card-text" style="overflow:hidden">Đây là bài tổng hợp tất cả ngữ pháp N3 có được</p>
                    <a href="@Url.Action("GroupPost","Search",new { name="N3"})" class="btn btn-primary">Tiếp tục</a>
                </div>
                <hr />
                <div class="card-body">
                    <h6 class="card-title">Tổng hợp ngữ pháp N2</h6>
                    <p class="card-text" style="overflow:hidden">Đây là bài tổng hợp tất cả ngữ pháp N2 có được</p>
                    <a href="@Url.Action("GroupPost","Search",new { name="N2"})" class="btn btn-primary">Tiếp tục</a>
                </div>
                <hr />
                <div class="card-body">
                    <h6 class="card-title">Tổng hợp ngữ pháp N1</h6>
                    <p class="card-text" style="overflow:hidden">Đây là bài tổng hợp tất cả ngữ pháp N1 có được</p>
                    <a href="@Url.Action("GroupPost","Search",new { name="N1"})" class="btn btn-primary">Tiếp tục</a>
                </div>

            </div>
            <hr class="d-sm-none">
            
        </div>
    </div>
</div>